In [37]:
%matplotlib inline

In [51]:
import torch
x = torch.randn(1, requires_grad=True) + torch.randn(1)
print(x)
y = torch.randn(2, requires_grad=True).sum()
print(y)
z = torch.randn(2, requires_grad=True).mean()
print(z)

a = torch.randn(2, requires_grad=True)
print(a)
print(a.mul(2))

tensor([-0.5571], grad_fn=<AddBackward0>)
tensor(0.0818, grad_fn=<SumBackward0>)
tensor(-0.1333, grad_fn=<MeanBackward0>)
tensor([ 0.6497, -0.7352], requires_grad=True)
tensor([ 1.2995, -1.4703], grad_fn=<MulBackward0>)


In [39]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [40]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [41]:
print(y.grad_fn)

In [24]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [25]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [26]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [27]:
out.backward()

In [28]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [29]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([  432.4510,  -522.7213, -1447.4696], grad_fn=<MulBackward0>)


In [30]:
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(gradients)

print(x.grad)

tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])


In [35]:
gradients

tensor([1.0000e-01, 1.0000e+00, 1.0000e-04])

In [36]:
y

tensor([  432.4510,  -522.7213, -1447.4696], grad_fn=<MulBackward0>)